language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
    - data
before_script:
  - npm run prepare-data
after_script:
  - npm install coveralls && cat ./coverage/lcov.info | coveralls
